apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiter
spec:
  replicas: 3  # <--- RUNNING 3 COPIES!
  selector:
    matchLabels:
      app: rate-limiter
  template:
    metadata:
      labels:
        app: rate-limiter
    spec:
      containers:
        - name: rate-limiter
          image: rate-limiter:latest # Must match your local build tag
          imagePullPolicy: Never     # Use local image
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ADDR
              value: "my-redis:6379" # Connects to the Service above