apiVersion: v1
kind: Service
metadata:
  name: rate-limiter-service
spec:
  type: NodePort
  selector:
    app: rate-limiter
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 # Access via localhost:30000